---
script: "./script/cibuild"
gemfile: "this/does/not/exist"
rvm:
  - "1.8.7"
matrix:
env:
  global:
    - secure: SiRiP4Lt2ws/xknWEcK1jyHJVfg3T5tkuUQ+NXOgJqfbrDHEmxqF9ctk8ESH6XOzaDPQ0ztb9SiUBtHIFqA9FLnCvKDEI0DsSy5QylSHLMj/SXHXDXvuiXnz39Vdx7vunEDGqfHG3sMpPy29spKifBMpEFKujJeRqf9YG3k9RU8=
